In [ ]:
import pandas as pd

datasets_path = r'C:\Users\omoy1\Desktop\brv_filtered\brv_datasets.csv'
features_df = pd.read_csv(datasets_path)
features_df.head()

,Ticker,Company_Name,Last_Date,Last_Price,Stage,Signal,Detect_Date,Detect_Price,Note,RSI,...,BB_Width_Zscore20,Lower_Shadow_Pct,Volume_Ratio,Valley_Body_Pct,Valley_Range_Pct,Volume_Zscore20,Filter_Relative_Pos,Buy_Price,Profit_Pct,Target_Profit
0,1379.T,HOKUTO CORP,2026-06-12,1898.0,3rd_VALLEY,BID,2024-11-15,1727.0,Valley+LowerShadow+VolumeSpike,29.48,...,3.83,2.07,2.55,0.47,3.25,1.99,0,1727.0,7.064273,1
1,1381.T,AXYZ,2026-06-12,3705.0,3rd_VALLEY,BID,2025-06-24,3105.0,Valley+LowerShadow+VolumeSpike,20.75,...,-0.69,2.31,1.73,1.14,2.31,1.30,0,3105.0,-3.059581,0
2,1401.T,MBS INC,2026-03-19,1401.0,3rd_VALLEY,BID,2025-04-07,630.0,Valley+LowerShadow+VolumeSpike,22.20,...,3.79,2.77,3.42,2.77,5.55,2.83,0,630.0,13.174603,1
3,1401.T,MBS INC,2026-03-19,1401.0,3rd_VALLEY,BID,2025-04-09,599.0,Valley+LowerShadow+VolumeSpike,20.83,...,2.60,3.63,4.16,3.63,6.06,2.97,0,599.0,19.031720,1
4,1417.T,MIRAIT ONE CORPORATION,2026-06-12,3777.0,3rd_VALLEY,BID,2025-04-07,1945.5,Valley+LowerShadow+VolumeSpike,21.64,...,2.96,4.60,1.88,2.39,6.61,2.16,0,1945.5,28.681573,1

#### 指標① 勝率

In [ ]:
def analyze_feature(df, feature):
    
    work = df[[feature, "Target_Profit", "Profit_Pct"]].copy()

    work["Bin"] = pd.qcut(
        work[feature],
        q=5,
        duplicates="drop"
    )

    result = work.groupby("Bin", observed=True).agg(
        Count=("Target_Profit", "count"),
        WinRate=("Target_Profit", "mean"),
        AvgProfit=("Profit_Pct", "mean"),
        MedianProfit=("Profit_Pct", "median"),
    )

    return result

In [ ]:
for col in features_df.columns:
    print(
        f"{col:<25}",
        features_df[col].dtype
    )

Ticker                    object
Company_Name              object
Last_Date                 object
Last_Price                float64
Stage                     object
Signal                    object
Detect_Date               object
Detect_Price              float64
Note                      object
RSI                       float64
Prev_RSI                  float64
RSI_Diff                  float64
RSI_Drop_Pct              float64
RSI_Depth                 float64
RSI_Down_Streak           float64
RSI_Rank20                float64
RSI_Zscore20              float64
BB_Days                   float64
BB_Close_Ratio            float64
BB_Touch_Ratio            float64
BB_Width                  float64
BB_Position               float64
BB_Width_Zscore20         float64
Lower_Shadow_Pct          float64
Volume_Ratio              float64
Valley_Body_Pct           float64
Valley_Range_Pct          float64
Volume_Zscore20           float64
Filter_Relative_Pos       int64
Buy_Price                 float64
Profit_Pct                float64
Target_Profit             int64

In [ ]:
feature_cols = features_df.select_dtypes(include=["number"]).columns.tolist()

exclude_cols = [
    "Target_Profit",
    "Profit_Pct",
    "Buy_Price",
    "Filter_Relative_Pos",
    "Detect_Price",
    "Last_Price",
]
feature_cols = [col for col in features_df.columns if col in feature_cols and col not in exclude_cols]

# Analyze all features
for col in feature_cols:
    print(f"\n=== {col} ===")
    display(analyze_feature(features_df, col))

=== RSI ===

                 Count   WinRate  AvgProfit  MedianProfit
Bin
(8.329, 23.69]     344  0.523256   8.829865      5.660046
(23.69, 26.668]    340  0.550000   9.246861      6.604144
(26.668, 28.26]    343  0.498542   8.706109      4.886770
(28.26, 29.29]     347  0.515850   9.124006      5.374823
(29.29, 30.0]      336  0.520833   8.507830      5.416208

=== Prev_RSI ===

                  Count   WinRate  AvgProfit  MedianProfit
Bin
(30.009, 31.258]    342  0.540936   9.511993      6.266136
(31.258, 32.826]    342  0.564327   9.837070      7.196629
(32.826, 35.08]     345  0.556522   9.767507      7.453875
(35.08, 38.994]     339  0.516224   9.263032      5.339266
(38.994, 83.91]     342  0.429825   6.037794      3.569878

=== RSI_Diff ===

                   Count   WinRate  AvgProfit  MedianProfit
Bin
(-57.311, -13.45]    343  0.454810   6.740012      4.059540
(-13.45, -9.732]     341  0.551320   8.958304      6.380368
(-9.732, -6.32]      343  0.536443  10.293550      6.794872
(-6.32, -3.44]       342  0.532164   9.578612      6.281170
(-3.44, -0.19]       341  0.533724   8.853619      5.973182

=== RSI_Drop_Pct ===

                               Count   WinRate  AvgProfit  MedianProfit
Bin
(-76.48100000000001, -36.184]    342  0.479532   7.109764      4.324940
(-36.184, -27.204]               342  0.505848   8.527840      5.171179
(-27.204, -18.628]               342  0.552632  10.323637      7.227042
(-18.628, -10.78]                342  0.532164   9.609460      6.281170
(-10.78, -0.63]                  342  0.538012   8.851121      6.266136

=== RSI_Depth ===

                Count   WinRate  AvgProfit  MedianProfit
Bin
(0.189, 3.44]     344  0.531977   8.803511      5.907553
(3.44, 6.32]      341  0.530792   9.587634      6.176471
(6.32, 9.732]     341  0.539589  10.345648      7.115532
(9.732, 13.45]    345  0.550725   9.039326      6.317044
(13.45, 57.31]    339  0.454277   6.631381      4.059540

=== RSI_Down_Streak ===

              Count   WinRate  AvgProfit  MedianProfit
Bin
(0.999, 2.0]    716  0.490223   7.992777      4.793242
(2.0, 3.0]      557  0.545781   9.404253      6.312769
(3.0, 4.0]      206  0.485437   8.709909      4.733099
(4.0, 12.0]     231  0.593074  10.549889      7.553777

=== RSI_Rank20 ===

               Count   WinRate  AvgProfit  MedianProfit
Bin
(4.999, 90.0]   1710  0.521637   8.884364      5.614646

=== RSI_Zscore20 ===

                             Count   WinRate  AvgProfit  MedianProfit
Bin
(-4.071000000000001, -2.82]    351  0.464387   6.437027      4.147465
(-2.82, -2.44]                 342  0.546784   8.765402      6.025312
(-2.44, -2.05]                 339  0.539823  11.156267      7.064273
(-2.05, -1.51]                 338  0.568047  10.081892      7.135186
(-1.51, 2.25]                  340  0.491176   8.074839      4.456295

=== BB_Days ===

               Count   WinRate  AvgProfit  MedianProfit
Bin
(1.999, 35.2]   1368  0.532164   9.003694      5.835288
(35.2, 269.0]    342  0.479532   8.407043      4.530732

=== BB_Close_Ratio ===

               Count   WinRate  AvgProfit  MedianProfit
Bin
(-0.001, 0.5]    770  0.497403   8.225894      4.902893
(0.5, 1.0]       940  0.541489   9.423749      6.167832

=== BB_Touch_Ratio ===

                Count   WinRate  AvgProfit  MedianProfit
Bin
(-0.001, 0.04]    363  0.482094   8.125166      4.504505
(0.04, 1.0]      1347  0.532294   9.088959      5.841924

=== BB_Width ===

                  Count   WinRate  AvgProfit  MedianProfit
Bin
(1.919, 10.352]     305  0.455738   6.188098      4.333333
(10.352, 15.15]     305  0.478689   7.394511      4.580521
(15.15, 21.222]     304  0.569079  10.495058      7.742437
(21.222, 29.308]    304  0.565789   9.752084      7.416927
(29.308, 178.15]    305  0.544262  10.963151      6.451613

=== BB_Position ===

                 Count   WinRate  AvgProfit  MedianProfit
Bin
(-0.691, -0.47]    327  0.525994   8.444777      5.892857
(-0.47, -0.34]     283  0.551237   8.743876      6.240250
(-0.34, -0.2]      311  0.508039   8.918094      5.360134
(-0.2, -0.06]      310  0.525806   9.665569      5.678120
(-0.06, 0.63]      292  0.503425   9.026628      5.239745

=== BB_Width_Zscore20 ===

               Count   WinRate  AvgProfit  MedianProfit
Bin
(-2.231, 0.0]    366  0.491803   8.448266      4.568013
(0.0, 1.76]      320  0.490625   8.622994      4.790303
(1.76, 2.65]     342  0.526316   8.693056      5.949381
(2.65, 3.192]    340  0.511765   8.754015      5.234578
(3.192, 4.24]    342  0.587719   9.916518      7.126908

=== Lower_Shadow_Pct ===

               Count   WinRate  AvgProfit  MedianProfit
Bin
(1.999, 2.46]    349  0.492837   7.696498      4.919016
(2.46, 3.02]     340  0.458824   7.056164      4.414125
(3.02, 3.85]     338  0.526627   8.683685      5.855502
(3.85, 5.22]     343  0.559767  10.356165      7.765885
(5.22, 25.13]    340  0.570588  10.646586      7.023471

=== Volume_Ratio ===

                            Count   WinRate  AvgProfit  MedianProfit
Bin
(1.2990000000000002, 1.62]    353  0.543909   9.182031      6.794872
(1.62, 2.0]                   333  0.573574   9.831051      7.688771
(2.0, 2.57]                   341  0.580645  11.095310      8.112324
(2.57, 3.72]                  342  0.505848   9.128955      5.196649
(3.72, 17.34]                 341  0.404692   5.195492      3.366649

=== Valley_Body_Pct ===

                  Count   WinRate  AvgProfit  MedianProfit
Bin
(-11.061, -1.29]    344  0.485465   8.009846      4.621764
(-1.29, 0.0]        350  0.491429   6.866056      4.562988
(0.0, 1.5]          334  0.491018   8.637539      4.878012
(1.5, 3.0]          342  0.517544   9.176710      6.288248
(3.0, 24.54]        340  0.623529  11.795245      8.200241

=== Valley_Range_Pct ===

                Count   WinRate  AvgProfit  MedianProfit
Bin
(2.019, 3.886]    342  0.301170   2.550769      1.097981
(3.886, 5.05]     344  0.447674   5.759754      3.955259
(5.05, 6.28]      341  0.574780   9.665150      7.513417
(6.28, 8.66]      342  0.637427  12.220502      9.455205
(8.66, 49.04]     341  0.648094  14.261924     10.784314

=== Volume_Zscore20 ===

                Count   WinRate  AvgProfit  MedianProfit
Bin
(0.159, 1.03]     345  0.513043   8.553842      5.276074
(1.03, 1.61]      341  0.524927   9.236961      6.471306
(1.61, 2.404]     340  0.585294  10.434226      7.062807
(2.404, 3.222]    342  0.578947  11.095873      7.758840
(3.222, 4.25]     342  0.406433   5.113913      3.227490

In [ ]:
import sweetviz as sv

report = sv.analyze(features_df[feature_cols + ["Target_Profit"]])
report.show_html()

                                             |          | [  0%]   00:00 -> (? left)

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [ ]:
for col in feature_cols:
    print("\n" + "=" * 80)
    print(col)
    print("=" * 80)
    print(analyze_feature(features_df, col))

================================================================================
RSI
================================================================================
                 Count   WinRate  AvgProfit  MedianProfit
Bin
(8.329, 23.69]     344  0.523256   8.829865      5.660046
(23.69, 26.668]    340  0.550000   9.246861      6.604144
(26.668, 28.26]    343  0.498542   8.706109      4.886770
(28.26, 29.29]     347  0.515850   9.124006      5.374823
(29.29, 30.0]      336  0.520833   8.507830      5.416208

================================================================================
Prev_RSI
================================================================================
                  Count   WinRate  AvgProfit  MedianProfit
Bin
(30.009, 31.258]    342  0.540936   9.511993      6.266136
(31.258, 32.826]    342  0.564327   9.837070      7.196629
(32.826, 35.08]     345  0.556522   9.767507      7.453875
(35.08, 38.994]     339  0.516224   9.263032      5.339266
(38.994, 83.91]     342  0.429825   6.037794      3.569878

================================================================================
RSI_Diff
================================================================================
                   Count   WinRate  AvgProfit  MedianProfit
Bin
(-57.311, -13.45]    343  0.454810   6.740012      4.059540
(-13.45, -9.732]     341  0.551320   8.958304      6.380368
(-9.732, -6.32]      343  0.536443  10.293550      6.794872
(-6.32, -3.44]       342  0.532164   9.578612      6.281170
(-3.44, -0.19]       341  0.533724   8.853619      5.973182

================================================================================
RSI_Drop_Pct
================================================================================
                               Count   WinRate  AvgProfit  MedianProfit
Bin
(-76.48100000000001, -36.184]    342  0.479532   7.109764      4.324940
(-36.184, -27.204]               342  0.505848   8.527840      5.171179
(-27.204, -18.628]               342  0.552632  10.323637      7.227042
(-18.628, -10.78]                342  0.532164   9.609460      6.281170
(-10.78, -0.63]                  342  0.538012   8.851121      6.266136

================================================================================
RSI_Depth
================================================================================
                Count   WinRate  AvgProfit  MedianProfit
Bin
(0.189, 3.44]     344  0.531977   8.803511      5.907553
(3.44, 6.32]      341  0.530792   9.587634      6.176471
(6.32, 9.732]     341  0.539589  10.345648      7.115532
(9.732, 13.45]    345  0.550725   9.039326      6.317044
(13.45, 57.31]    339  0.454277   6.631381      4.059540

================================================================================
RSI_Down_Streak
================================================================================
              Count   WinRate  AvgProfit  MedianProfit
Bin
(0.999, 2.0]    716  0.490223   7.992777      4.793242
(2.0, 3.0]      557  0.545781   9.404253      6.312769
(3.0, 4.0]      206  0.485437   8.709909      4.733099
(4.0, 12.0]     231  0.593074  10.549889      7.553777

================================================================================
RSI_Rank20
================================================================================
               Count   WinRate  AvgProfit  MedianProfit
Bin
(4.999, 90.0]   1710  0.521637   8.884364      5.614646

================================================================================
RSI_Zscore20
================================================================================
                             Count   WinRate  AvgProfit  MedianProfit
Bin
(-4.071000000000001, -2.82]    351  0.464387   6.437027      4.147465
(-2.82, -2.44]                 342  0.546784   8.765402      6.025312
(-2.44, -2.05]                 339  0.539823  11.156267      7.064273
(-2.05, -1.51]                 338  0.568047  10.081892      7.135186
(-1.51, 2.25]                  340  0.491176   8.074839      4.456295

================================================================================
BB_Days
================================================================================
               Count   WinRate  AvgProfit  MedianProfit
Bin
(1.999, 35.2]   1368  0.532164   9.003694      5.835288
(35.2, 269.0]    342  0.479532   8.407043      4.530732

================================================================================
BB_Close_Ratio
================================================================================
               Count   WinRate  AvgProfit  MedianProfit
Bin
(-0.001, 0.5]    770  0.497403   8.225894      4.902893
(0.5, 1.0]       940  0.541489   9.423749      6.167832

================================================================================
BB_Touch_Ratio
================================================================================
                Count   WinRate  AvgProfit  MedianProfit
Bin
(-0.001, 0.04]    363  0.482094   8.125166      4.504505
(0.04, 1.0]      1347  0.532294   9.088959      5.841924

================================================================================
BB_Width
================================================================================
                  Count   WinRate  AvgProfit  MedianProfit
Bin
(1.919, 10.352]     305  0.455738   6.188098      4.333333
(10.352, 15.15]     305  0.478689   7.394511      4.580521
(15.15, 21.222]     304  0.569079  10.495058      7.742437
(21.222, 29.308]    304  0.565789   9.752084      7.416927
(29.308, 178.15]    305  0.544262  10.963151      6.451613

================================================================================
BB_Position
================================================================================
                 Count   WinRate  AvgProfit  MedianProfit
Bin
(-0.691, -0.47]    327  0.525994   8.444777      5.892857
(-0.47, -0.34]     283  0.551237   8.743876      6.240250
(-0.34, -0.2]      311  0.508039   8.918094      5.360134
(-0.2, -0.06]      310  0.525806   9.665569      5.678120
(-0.06, 0.63]      292  0.503425   9.026628      5.239745

================================================================================
BB_Width_Zscore20
================================================================================
               Count   WinRate  AvgProfit  MedianProfit
Bin
(-2.231, 0.0]    366  0.491803   8.448266      4.568013
(0.0, 1.76]      320  0.490625   8.622994      4.790303
(1.76, 2.65]     342  0.526316   8.693056      5.949381
(2.65, 3.192]    340  0.511765   8.754015      5.234578
(3.192, 4.24]    342  0.587719   9.916518      7.126908

================================================================================
Lower_Shadow_Pct
================================================================================
               Count   WinRate  AvgProfit  MedianProfit
Bin
(1.999, 2.46]    349  0.492837   7.696498      4.919016
(2.46, 3.02]     340  0.458824   7.056164      4.414125
(3.02, 3.85]     338  0.526627   8.683685      5.855502
(3.85, 5.22]     343  0.559767  10.356165      7.765885
(5.22, 25.13]    340  0.570588  10.646586      7.023471

================================================================================
Volume_Ratio
================================================================================
                            Count   WinRate  AvgProfit  MedianProfit
Bin
(1.2990000000000002, 1.62]    353  0.543909   9.182031      6.794872
(1.62, 2.0]                   333  0.573574   9.831051      7.688771
(2.0, 2.57]                   341  0.580645  11.095310      8.112324
(2.57, 3.72]                  342  0.505848   9.128955      5.196649
(3.72, 17.34]                 341  0.404692   5.195492      3.366649

================================================================================
Valley_Body_Pct
================================================================================
                  Count   WinRate  AvgProfit  MedianProfit
Bin
(-11.061, -1.29]    344  0.485465   8.009846      4.621764
(-1.29, 0.0]        350  0.491429   6.866056      4.562988
(0.0, 1.5]          334  0.491018   8.637539      4.878012
(1.5, 3.0]          342  0.517544   9.176710      6.288248
(3.0, 24.54]        340  0.623529  11.795245      8.200241

================================================================================
Valley_Range_Pct
================================================================================
                Count   WinRate  AvgProfit  MedianProfit
Bin
(2.019, 3.886]    342  0.301170   2.550769      1.097981
(3.886, 5.05]     344  0.447674   5.759754      3.955259
(5.05, 6.28]      341  0.574780   9.665150      7.513417
(6.28, 8.66]      342  0.637427  12.220502      9.455205
(8.66, 49.04]     341  0.648094  14.261924     10.784314

================================================================================
Volume_Zscore20
================================================================================
                Count   WinRate  AvgProfit  MedianProfit
Bin
(0.159, 1.03]     345  0.513043   8.553842      5.276074
(1.03, 1.61]      341  0.524927   9.236961      6.471306
(1.61, 2.404]     340  0.585294  10.434226      7.062807
(2.404, 3.222]    342  0.578947  11.095873      7.758840
(3.222, 4.25]     342  0.406433   5.113913      3.227490

In [ ]:
from itertools import combinations
pairs = list(combinations(feature_cols, 2))

print(len(pairs))
for f1, f2 in pairs:
    print(f1, f2)

171
RSI Prev_RSI
RSI RSI_Diff
RSI RSI_Drop_Pct
RSI RSI_Depth
RSI RSI_Down_Streak
RSI RSI_Rank20
RSI RSI_Zscore20
RSI BB_Days
RSI BB_Close_Ratio
RSI BB_Touch_Ratio
RSI BB_Width
RSI BB_Position
RSI BB_Width_Zscore20
RSI Lower_Shadow_Pct
RSI Volume_Ratio
RSI Valley_Body_Pct
RSI Valley_Range_Pct
RSI Volume_Zscore20
Prev_RSI RSI_Diff
Prev_RSI RSI_Drop_Pct
Prev_RSI RSI_Depth
Prev_RSI RSI_Down_Streak
Prev_RSI RSI_Rank20
Prev_RSI RSI_Zscore20
Prev_RSI BB_Days
Prev_RSI BB_Close_Ratio
Prev_RSI BB_Touch_Ratio
Prev_RSI BB_Width
Prev_RSI BB_Position
Prev_RSI BB_Width_Zscore20
Prev_RSI Lower_Shadow_Pct
Prev_RSI Volume_Ratio
Prev_RSI Valley_Body_Pct
Prev_RSI Valley_Range_Pct
Prev_RSI Volume_Zscore20
RSI_Diff RSI_Drop_Pct
RSI_Diff RSI_Depth
RSI_Diff RSI_Down_Streak
RSI_Diff RSI_Rank20
RSI_Diff RSI_Zscore20
RSI_Diff BB_Days
RSI_Diff BB_Close_Ratio
RSI_Diff BB_Touch_Ratio
RSI_Diff BB_Width
RSI_Diff BB_Position
RSI_Diff BB_Width_Zscore20
RSI_Diff Lower_Shadow_Pct
RSI_Diff Volume_Ratio
RSI_Diff Valley_Body_Pct
RSI_Diff Valley_Range_Pct
RSI_Diff Volume_Zscore20
RSI_Drop_Pct RSI_Depth
RSI_Drop_Pct RSI_Down_Streak
RSI_Drop_Pct RSI_Rank20
RSI_Drop_Pct RSI_Zscore20
RSI_Drop_Pct BB_Days
RSI_Drop_Pct BB_Close_Ratio
RSI_Drop_Pct BB_Touch_Ratio
RSI_Drop_Pct BB_Width
RSI_Drop_Pct BB_Position
RSI_Drop_Pct BB_Width_Zscore20
RSI_Drop_Pct Lower_Shadow_Pct
RSI_Drop_Pct Volume_Ratio
RSI_Drop_Pct Valley_Body_Pct
RSI_Drop_Pct Valley_Range_Pct
RSI_Drop_Pct Volume_Zscore20
RSI_Depth RSI_Down_Streak
RSI_Depth RSI_Rank20
RSI_Depth RSI_Zscore20
RSI_Depth BB_Days
RSI_Depth BB_Close_Ratio
RSI_Depth BB_Touch_Ratio
RSI_Depth BB_Width
RSI_Depth BB_Position
RSI_Depth BB_Width_Zscore20
RSI_Depth Lower_Shadow_Pct
RSI_Depth Volume_Ratio
RSI_Depth Valley_Body_Pct
RSI_Depth Valley_Range_Pct
RSI_Depth Volume_Zscore20
RSI_Down_Streak RSI_Rank20
RSI_Down_Streak RSI_Zscore20
RSI_Down_Streak BB_Days
RSI_Down_Streak BB_Close_Ratio
RSI_Down_Streak BB_Touch_Ratio
RSI_Down_Streak BB_Width
RSI_Down_Streak BB_Position
RSI_Down_Streak BB_Width_Zscore20
RSI_Down_Streak Lower_Shadow_Pct
RSI_Down_Streak Volume_Ratio
RSI_Down_Streak Valley_Body_Pct
RSI_Down_Streak Valley_Range_Pct
RSI_Down_Streak Volume_Zscore20
RSI_Rank20 RSI_Zscore20
RSI_Rank20 BB_Days
RSI_Rank20 BB_Close_Ratio
RSI_Rank20 BB_Touch_Ratio
RSI_Rank20 BB_Width
RSI_Rank20 BB_Position
RSI_Rank20 BB_Width_Zscore20
RSI_Rank20 Lower_Shadow_Pct
RSI_Rank20 Volume_Ratio
RSI_Rank20 Valley_Body_Pct
RSI_Rank20 Valley_Range_Pct
RSI_Rank20 Volume_Zscore20
RSI_Zscore20 BB_Days
RSI_Zscore20 BB_Close_Ratio
RSI_Zscore20 BB_Touch_Ratio
RSI_Zscore20 BB_Width
RSI_Zscore20 BB_Position
RSI_Zscore20 BB_Width_Zscore20
RSI_Zscore20 Lower_Shadow_Pct
RSI_Zscore20 Volume_Ratio
RSI_Zscore20 Valley_Body_Pct
RSI_Zscore20 Valley_Range_Pct
RSI_Zscore20 Volume_Zscore20
BB_Days BB_Close_Ratio
BB_Days BB_Touch_Ratio
BB_Days BB_Width
BB_Days BB_Position
BB_Days BB_Width_Zscore20
BB_Days Lower_Shadow_Pct
BB_Days Volume_Ratio
BB_Days Valley_Body_Pct
BB_Days Valley_Range_Pct
BB_Days Volume_Zscore20
BB_Close_Ratio BB_Touch_Ratio
BB_Close_Ratio BB_Width
BB_Close_Ratio BB_Position
BB_Close_Ratio BB_Width_Zscore20
BB_Close_Ratio Lower_Shadow_Pct
BB_Close_Ratio Volume_Ratio
BB_Close_Ratio Valley_Body_Pct
BB_Close_Ratio Valley_Range_Pct
BB_Close_Ratio Volume_Zscore20
BB_Touch_Ratio BB_Width
BB_Touch_Ratio BB_Position
BB_Touch_Ratio BB_Width_Zscore20
BB_Touch_Ratio Lower_Shadow_Pct
BB_Touch_Ratio Volume_Ratio
BB_Touch_Ratio Valley_Body_Pct
BB_Touch_Ratio Valley_Range_Pct
BB_Touch_Ratio Volume_Zscore20
BB_Width BB_Position
BB_Width BB_Width_Zscore20
BB_Width Lower_Shadow_Pct
BB_Width Volume_Ratio
BB_Width Valley_Body_Pct
BB_Width Valley_Range_Pct
BB_Width Volume_Zscore20
BB_Position BB_Width_Zscore20
BB_Position Lower_Shadow_Pct
BB_Position Volume_Ratio
BB_Position Valley_Body_Pct
BB_Position Valley_Range_Pct
BB_Position Volume_Zscore20
BB_Width_Zscore20 Lower_Shadow_Pct
BB_Width_Zscore20 Volume_Ratio
BB_Width_Zscore20 Valley_Body_Pct
BB_Width_Zscore20 Valley_Range_Pct
BB_Width_Zscore20 Volume_Zscore20
Lower_Shadow_Pct Volume_Ratio
Lower_Shadow_Pct Valley_Body_Pct
Lower_Shadow_Pct Valley_Range_Pct
Lower_Shadow_Pct Volume_Zscore20
Volume_Ratio Valley_Body_Pct
Volume_Ratio Valley_Range_Pct
Volume_Ratio Volume_Zscore20
Valley_Body_Pct Valley_Range_Pct
Valley_Body_Pct Volume_Zscore20
Valley_Range_Pct Volume_Zscore20

In [ ]:
top_features = [
    "RSI_Down_Streak",
    "RSI",
    "RSI_Diff",
    "RSI_Zscore20",
    "BB_Days",
    "Volume_Ratio",
]
summary = []

for f1, f2 in combinations(top_features, 2):

    table = pd.crosstab(
        pd.qcut(features_df[f1], q=4, duplicates="drop"),
        pd.qcut(features_df[f2], q=4, duplicates="drop"),
        values=features_df["Target_Profit"],
        aggfunc="mean"
    )

    summary.append({
        "Feature1": f1,
        "Feature2": f2,
        "BestWinRate": table.max().max()
    })

summary_df = pd.DataFrame(summary)
summary_df.sort_values(
    "BestWinRate",
    ascending=False
)

           Feature1      Feature2  BestWinRate
13     RSI_Zscore20  Volume_Ratio     0.707865
2   RSI_Down_Streak  RSI_Zscore20     0.692308
4   RSI_Down_Streak  Volume_Ratio     0.690909
1   RSI_Down_Streak      RSI_Diff     0.652174
0   RSI_Down_Streak           RSI     0.649123
8               RSI  Volume_Ratio     0.631068
9          RSI_Diff  RSI_Zscore20     0.630769
3   RSI_Down_Streak       BB_Days     0.617143
6               RSI  RSI_Zscore20     0.613445
12     RSI_Zscore20       BB_Days     0.612903
11         RSI_Diff  Volume_Ratio     0.612903
14          BB_Days  Volume_Ratio     0.599369
5               RSI      RSI_Diff     0.593750
10         RSI_Diff       BB_Days     0.567485
7               RSI       BB_Days     0.560976

In [ ]:
df = features_df.copy()

def analyze_pair(df, feature1, feature2, bins=3):
    work = df.copy()

    work[f"{feature1}_Bin"] = pd.qcut(
        work[feature1],
        q=bins,
        duplicates="drop"
    )

    work[f"{feature2}_Bin"] = pd.qcut(
        work[feature2],
        q=bins,
        duplicates="drop"
    )

    winrate = pd.pivot_table(
        work,
        values="Target_Profit",
        index=f"{feature1}_Bin",
        columns=f"{feature2}_Bin",
        aggfunc="mean",
        observed=False
    )

    count = pd.pivot_table(
        work,
        values="Target_Profit",
        index=f"{feature1}_Bin",
        columns=f"{feature2}_Bin",
        aggfunc="count",
        observed=False
    )

    print("=" * 80)
    print(f"{feature1} × {feature2}")
    print("\n【WinRate】")
    print(winrate)

    print("\n【Count】")
    print(count)

    return winrate, count

from itertools import combinations

for f1, f2 in combinations(feature_cols, 2):

    # print("=" * 80)
    # print(f"{f1} × {f2}")

    analyze_pair(df, f1, f2)

================================================================================
RSI × Prev_RSI

【WinRate】
Prev_RSI_Bin     (30.009, 32.3]  (32.3, 36.033]  (36.033, 83.91]
RSI_Bin
(8.329, 25.767]        0.566474        0.567839         0.454545
(25.767, 28.73]        0.517588        0.526627         0.490196
(28.73, 30.0]          0.557789        0.572139         0.434524

【Count】
Prev_RSI_Bin     (30.009, 32.3]  (32.3, 36.033]  (36.033, 83.91]
RSI_Bin
(8.329, 25.767]             173             199              198
(25.767, 28.73]             199             169              204
(28.73, 30.0]               199             201              168
================================================================================
RSI × RSI_Diff

【WinRate】
RSI_Diff_Bin     (-57.311, -10.833]  (-10.833, -5.15]  (-5.15, -0.19]
RSI_Bin
(8.329, 25.767]            0.527697          0.531818        0.428571
(25.767, 28.73]            0.479452          0.541872        0.502242
(28.73, 30.0]              0.419753          0.513514        0.557522

【Count】
RSI_Diff_Bin     (-57.311, -10.833]  (-10.833, -5.15]  (-5.15, -0.19]
RSI_Bin
(8.329, 25.767]                 343               220               7
(25.767, 28.73]                 146               203             223
(28.73, 30.0]                    81               148             339
================================================================================
RSI × RSI_Drop_Pct

【WinRate】
RSI_Drop_Pct_Bin  (-76.48100000000001, -30.063]  (-30.063, -15.46]  \
RSI_Bin
(8.329, 25.767]                        0.525641           0.533333
(25.767, 28.73]                        0.487603           0.529661
(28.73, 30.0]                          0.423729           0.487013

RSI_Drop_Pct_Bin  (-15.46, -0.63]
RSI_Bin
(8.329, 25.767]               NaN
(25.767, 28.73]          0.502326
(28.73, 30.0]            0.560563

【Count】
RSI_Drop_Pct_Bin  (-76.48100000000001, -30.063]  (-30.063, -15.46]  \
RSI_Bin
(8.329, 25.767]                             390                180
(25.767, 28.73]                             121                236
(28.73, 30.0]                                59                154

RSI_Drop_Pct_Bin  (-15.46, -0.63]
RSI_Bin
(8.329, 25.767]                 0
(25.767, 28.73]               215
(28.73, 30.0]                 355
================================================================================
RSI × RSI_Depth

【WinRate】
RSI_Depth_Bin    (0.189, 5.15]  (5.15, 10.833]  (10.833, 57.31]
RSI_Bin
(8.329, 25.767]       0.428571        0.531818         0.527697
(25.767, 28.73]       0.502242        0.541872         0.479452
(28.73, 30.0]         0.557185        0.513699         0.419753

【Count】
RSI_Depth_Bin    (0.189, 5.15]  (5.15, 10.833]  (10.833, 57.31]
RSI_Bin
(8.329, 25.767]              7             220              343
(25.767, 28.73]            223             203              146
(28.73, 30.0]              341             146               81
================================================================================
RSI × RSI_Down_Streak

【WinRate】
RSI_Down_Streak_Bin  (0.999, 2.0]  (2.0, 3.0]  (3.0, 12.0]
RSI_Bin
(8.329, 25.767]          0.445087    0.561538     0.569343
(25.767, 28.73]          0.509881    0.526316     0.493243
(28.73, 30.0]            0.500000    0.539683     0.565789

【Count】
RSI_Down_Streak_Bin  (0.999, 2.0]  (2.0, 3.0]  (3.0, 12.0]
RSI_Bin
(8.329, 25.767]               173         260          137
(25.767, 28.73]               253         171          148
(28.73, 30.0]                 290         126          152
================================================================================
RSI × RSI_Rank20

【WinRate】
RSI_Rank20_Bin   (4.999, 90.0]
RSI_Bin
(8.329, 25.767]       0.528070
(25.767, 28.73]       0.510490
(28.73, 30.0]         0.526408

【Count】
RSI_Rank20_Bin   (4.999, 90.0]
RSI_Bin
(8.329, 25.767]            570
(25.767, 28.73]            572
(28.73, 30.0]              568
================================================================================
RSI × RSI_Zscore20

【WinRate】
RSI_Zscore20_Bin  (-4.071000000000001, -2.55]  (-2.55, -1.9]  (-1.9, 2.25]
RSI_Bin
(8.329, 25.767]                      0.504644       0.602151      0.426230
(25.767, 28.73]                      0.503030       0.551724      0.475490
(28.73, 30.0]                        0.458824       0.489011      0.568106

【Count】
RSI_Zscore20_Bin  (-4.071000000000001, -2.55]  (-2.55, -1.9]  (-1.9, 2.25]
RSI_Bin
(8.329, 25.767]                           323            186            61
(25.767, 28.73]                           165            203           204
(28.73, 30.0]                              85            182           301
================================================================================
RSI × BB_Days

【WinRate】
BB_Days_Bin      (1.999, 8.0]  (8.0, 269.0]
RSI_Bin
(8.329, 25.767]      0.529545      0.523077
(25.767, 28.73]      0.538462      0.456410
(28.73, 30.0]        0.536364      0.512605

【Count】
BB_Days_Bin      (1.999, 8.0]  (8.0, 269.0]
RSI_Bin
(8.329, 25.767]           440           130
(25.767, 28.73]           377           195
(28.73, 30.0]             330           238
================================================================================
RSI × BB_Close_Ratio

【WinRate】
BB_Close_Ratio_Bin  (-0.001, 0.04]  (0.04, 1.0]
RSI_Bin
(8.329, 25.767]           0.514706     0.532258
(25.767, 28.73]           0.473684     0.528796
(28.73, 30.0]             0.510949     0.540816

【Count】
BB_Close_Ratio_Bin  (-0.001, 0.04]  (0.04, 1.0]
RSI_Bin
(8.329, 25.767]                136          434
(25.767, 28.73]                190          382
(28.73, 30.0]                  274          294
================================================================================
RSI × BB_Touch_Ratio

【WinRate】
BB_Touch_Ratio_Bin  (-0.001, 0.13]  (0.13, 1.0]
RSI_Bin
(8.329, 25.767]           0.519084     0.530752
(25.767, 28.73]           0.459893     0.535065
(28.73, 30.0]             0.498024     0.549206

【Count】
BB_Touch_Ratio_Bin  (-0.001, 0.13]  (0.13, 1.0]
RSI_Bin
(8.329, 25.767]                131          439
(25.767, 28.73]                187          385
(28.73, 30.0]                  253          315
================================================================================
RSI × BB_Width

【WinRate】
BB_Width_Bin     (1.919, 13.36]  (13.36, 23.487]  (23.487, 178.15]
RSI_Bin
(8.329, 25.767]        0.408759         0.603448          0.554113
(25.767, 28.73]        0.533333         0.481707          0.539474
(28.73, 30.0]          0.460733         0.562130          0.536000

【Count】
BB_Width_Bin     (1.919, 13.36]  (13.36, 23.487]  (23.487, 178.15]
RSI_Bin
(8.329, 25.767]             137              174               231
(25.767, 28.73]             180              164               152
(28.73, 30.0]               191              169               125
================================================================================
RSI × BB_Position

【WinRate】
BB_Position_Bin  (-0.691, -0.38]  (-0.38, -0.16]  (-0.16, 0.63]
RSI_Bin
(8.329, 25.767]         0.543956        0.517007       0.483871
(25.767, 28.73]         0.518182        0.523364       0.511628
(28.73, 30.0]           0.522727        0.471831       0.535117

【Count】
BB_Position_Bin  (-0.691, -0.38]  (-0.38, -0.16]  (-0.16, 0.63]
RSI_Bin
(8.329, 25.767]              364             147             31
(25.767, 28.73]              110             214            172
(28.73, 30.0]                 44             142            299
================================================================================
RSI × BB_Width_Zscore20

【WinRate】
BB_Width_Zscore20_Bin  (-2.231, 1.29]  (1.29, 2.86]  (2.86, 4.24]
RSI_Bin
(8.329, 25.767]              0.369565      0.567376      0.554896
(25.767, 28.73]              0.507463      0.481308      0.554140
(28.73, 30.0]                0.517986      0.511628      0.600000

【Count】
BB_Width_Zscore20_Bin  (-2.231, 1.29]  (1.29, 2.86]  (2.86, 4.24]
RSI_Bin
(8.329, 25.767]                    92           141           337
(25.767, 28.73]                   201           214           157
(28.73, 30.0]                     278           215            75
================================================================================
RSI × Lower_Shadow_Pct

【WinRate】
Lower_Shadow_Pct_Bin  (1.999, 2.82]  (2.82, 4.247]  (4.247, 25.13]
RSI_Bin
(8.329, 25.767]            0.490385       0.513228        0.589595
(25.767, 28.73]            0.468599       0.474286        0.589474
(28.73, 30.0]              0.506329       0.497537        0.570048

【Count】
Lower_Shadow_Pct_Bin  (1.999, 2.82]  (2.82, 4.247]  (4.247, 25.13]
RSI_Bin
(8.329, 25.767]                 208            189             173
(25.767, 28.73]                 207            175             190
(28.73, 30.0]                   158            203             207
================================================================================
RSI × Volume_Ratio

【WinRate】
Volume_Ratio_Bin  (1.2990000000000002, 1.86]  (1.86, 2.833]  (2.833, 17.34]
RSI_Bin
(8.329, 25.767]                     0.566138       0.584699        0.439394
(25.767, 28.73]                     0.544186       0.554945        0.422857
(28.73, 30.0]                       0.534483       0.598985        0.446701

【Count】
Volume_Ratio_Bin  (1.2990000000000002, 1.86]  (1.86, 2.833]  (2.833, 17.34]
RSI_Bin
(8.329, 25.767]                          189            183             198
(25.767, 28.73]                          215            182             175
(28.73, 30.0]                            174            197             197
================================================================================
RSI × Valley_Body_Pct

【WinRate】
Valley_Body_Pct_Bin  (-11.061, -0.333]  (-0.333, 1.95]  (1.95, 24.54]
RSI_Bin
(8.329, 25.767]               0.481283        0.520202       0.583784
(25.767, 28.73]               0.479798        0.442623       0.607330
(28.73, 30.0]                 0.464865        0.557292       0.554974

【Count】
Valley_Body_Pct_Bin  (-11.061, -0.333]  (-0.333, 1.95]  (1.95, 24.54]
RSI_Bin
(8.329, 25.767]                    187             198            185
(25.767, 28.73]                    198             183            191
(28.73, 30.0]                      185             192            191
================================================================================
RSI × Valley_Range_Pct

【WinRate】
Valley_Range_Pct_Bin  (2.019, 4.65]  (4.65, 6.87]  (6.87, 49.04]
RSI_Bin
(8.329, 25.767]            0.326316      0.597156       0.668639
(25.767, 28.73]            0.358209      0.522843       0.672414
(28.73, 30.0]              0.403315      0.559006       0.601770

【Count】
Valley_Range_Pct_Bin  (2.019, 4.65]  (4.65, 6.87]  (6.87, 49.04]
RSI_Bin
(8.329, 25.767]                 190           211            169
(25.767, 28.73]                 201           197            174
(28.73, 30.0]                   181           161            226
================================================================================
RSI × Volume_Zscore20

【WinRate】
Volume_Zscore20_Bin  (0.159, 1.4]  (1.4, 2.613]  (2.613, 4.25]
RSI_Bin
(8.329, 25.767]          0.507937      0.596859       0.478947
(25.767, 28.73]          0.531100      0.519126       0.477778
(28.73, 30.0]            0.520000      0.595855       0.465000

【Count】
Volume_Zscore20_Bin  (0.159, 1.4]  (1.4, 2.613]  (2.613, 4.25]
RSI_Bin
(8.329, 25.767]               189           191            190
(25.767, 28.73]               209           183            180
(28.73, 30.0]                 175           193            200
================================================================================
Prev_RSI × RSI_Diff

【WinRate】
RSI_Diff_Bin     (-57.311, -10.833]  (-10.833, -5.15]  (-5.15, -0.19]
Prev_RSI_Bin
(30.009, 32.3]             0.609756          0.559701        0.535354
(32.3, 36.033]             0.628571          0.546392        0.531792
(36.033, 83.91]            0.457547          0.472603             NaN

【Count】
RSI_Diff_Bin     (-57.311, -10.833]  (-10.833, -5.15]  (-5.15, -0.19]
Prev_RSI_Bin
(30.009, 32.3]                   41               134             396
(32.3, 36.033]                  105               291             173
(36.033, 83.91]                 424               146               0
================================================================================
Prev_RSI × RSI_Drop_Pct

【WinRate】
RSI_Drop_Pct_Bin  (-76.48100000000001, -30.063]  (-30.063, -15.46]  \
Prev_RSI_Bin
(30.009, 32.3]                         0.594595           0.543103
(32.3, 36.033]                         0.591667           0.553846
(36.033, 83.91]                        0.462766           0.458763

RSI_Drop_Pct_Bin  (-15.46, -0.63]
Prev_RSI_Bin
(30.009, 32.3]           0.538058
(32.3, 36.033]           0.539683
(36.033, 83.91]               NaN

【Count】
RSI_Drop_Pct_Bin  (-76.48100000000001, -30.063]  (-30.063, -15.46]  \
Prev_RSI_Bin
(30.009, 32.3]                               74                116
(32.3, 36.033]                              120                260
(36.033, 83.91]                             376                194

RSI_Drop_Pct_Bin  (-15.46, -0.63]
Prev_RSI_Bin
(30.009, 32.3]                381
(32.3, 36.033]                189
(36.033, 83.91]                 0
================================================================================
Prev_RSI × RSI_Depth

【WinRate】
RSI_Depth_Bin    (0.189, 5.15]  (5.15, 10.833]  (10.833, 57.31]
Prev_RSI_Bin
(30.009, 32.3]        0.535354        0.559701         0.609756
(32.3, 36.033]        0.531429        0.546713         0.628571
(36.033, 83.91]            NaN        0.472603         0.457547

【Count】
RSI_Depth_Bin    (0.189, 5.15]  (5.15, 10.833]  (10.833, 57.31]
Prev_RSI_Bin
(30.009, 32.3]             396             134               41
(32.3, 36.033]             175             289              105
(36.033, 83.91]              0             146              424
================================================================================
Prev_RSI × RSI_Down_Streak

【WinRate】
RSI_Down_Streak_Bin  (0.999, 2.0]  (2.0, 3.0]  (3.0, 12.0]
Prev_RSI_Bin
(30.009, 32.3]           0.485000    0.613095     0.551724
(32.3, 36.033]           0.548523    0.561111     0.565789
(36.033, 83.91]          0.444444    0.478469     0.475610

【Count】
RSI_Down_Streak_Bin  (0.999, 2.0]  (2.0, 3.0]  (3.0, 12.0]
Prev_RSI_Bin
(30.009, 32.3]                200         168          203
(32.3, 36.033]                237         180          152
(36.033, 83.91]               279         209           82
================================================================================
Prev_RSI × RSI_Rank20

【WinRate】
RSI_Rank20_Bin   (4.999, 90.0]
Prev_RSI_Bin
(30.009, 32.3]        0.546410
(32.3, 36.033]        0.557118
(36.033, 83.91]       0.461404

【Count】
RSI_Rank20_Bin   (4.999, 90.0]
Prev_RSI_Bin
(30.009, 32.3]             571
(32.3, 36.033]             569
(36.033, 83.91]            570
================================================================================
Prev_RSI × RSI_Zscore20

【WinRate】
RSI_Zscore20_Bin  (-4.071000000000001, -2.55]  (-2.55, -1.9]  (-1.9, 2.25]
Prev_RSI_Bin
(30.009, 32.3]                       0.564706       0.570681      0.525424
(32.3, 36.033]                       0.549669       0.597285      0.517766
(36.033, 83.91]                      0.456973       0.452830      0.500000

【Count】
RSI_Zscore20_Bin  (-4.071000000000001, -2.55]  (-2.55, -1.9]  (-1.9, 2.25]
Prev_RSI_Bin
(30.009, 32.3]                             85            191           295
(32.3, 36.033]                            151            221           197
(36.033, 83.91]                           337            159            74
================================================================================
Prev_RSI × BB_Days

【WinRate】
BB_Days_Bin      (1.999, 8.0]  (8.0, 269.0]
Prev_RSI_Bin
(30.009, 32.3]       0.576220      0.506173
(32.3, 36.033]       0.587131      0.500000
(36.033, 83.91]      0.459641      0.467742

【Count】
BB_Days_Bin      (1.999, 8.0]  (8.0, 269.0]
Prev_RSI_Bin
(30.009, 32.3]            328           243
(32.3, 36.033]            373           196
(36.033, 83.91]           446           124
================================================================================
Prev_RSI × BB_Close_Ratio

【WinRate】
BB_Close_Ratio_Bin  (-0.001, 0.04]  (0.04, 1.0]
Prev_RSI_Bin
(30.009, 32.3]            0.511719     0.574603
(32.3, 36.033]            0.493023     0.596045
(36.033, 83.91]           0.488372     0.453515

【Count】
BB_Close_Ratio_Bin  (-0.001, 0.04]  (0.04, 1.0]
Prev_RSI_Bin
(30.009, 32.3]                 256          315
(32.3, 36.033]                 215          354
(36.033, 83.91]                129          441
================================================================================
Prev_RSI × BB_Touch_Ratio

【WinRate】
BB_Touch_Ratio_Bin  (-0.001, 0.13]  (0.13, 1.0]
Prev_RSI_Bin
(30.009, 32.3]            0.498008     0.584375
(32.3, 36.033]            0.492308     0.590909
(36.033, 83.91]           0.472000     0.458427

【Count】
BB_Touch_Ratio_Bin  (-0.001, 0.13]  (0.13, 1.0]
Prev_RSI_Bin
(30.009, 32.3]                 251          320
(32.3, 36.033]                 195          374
(36.033, 83.91]                125          445
================================================================================
Prev_RSI × BB_Width

【WinRate】
BB_Width_Bin     (1.919, 13.36]  (13.36, 23.487]  (23.487, 178.15]
Prev_RSI_Bin
(30.009, 32.3]         0.562044         0.500000          0.610811
(32.3, 36.033]         0.481481         0.612717          0.551724
(36.033, 83.91]        0.406699         0.532967          0.456376

【Count】
BB_Width_Bin     (1.919, 13.36]  (13.36, 23.487]  (23.487, 178.15]
Prev_RSI_Bin
(30.009, 32.3]              137              152               185
(32.3, 36.033]              162              173               174
(36.033, 83.91]             209              182               149
================================================================================
Prev_RSI × BB_Position

【WinRate】
BB_Position_Bin  (-0.691, -0.38]  (-0.38, -0.16]  (-0.16, 0.63]
Prev_RSI_Bin
(30.009, 32.3]          0.611111        0.519380       0.564706
(32.3, 36.033]          0.603053        0.561497       0.502618
(36.033, 83.91]         0.484848        0.443850       0.410714

【Count】
BB_Position_Bin  (-0.691, -0.38]  (-0.38, -0.16]  (-0.16, 0.63]
Prev_RSI_Bin
(30.009, 32.3]                90             129            255
(32.3, 36.033]               131             187            191
(36.033, 83.91]              297             187             56
================================================================================
Prev_RSI × BB_Width_Zscore20

【WinRate】
BB_Width_Zscore20_Bin  (-2.231, 1.29]  (1.29, 2.86]  (2.86, 4.24]
Prev_RSI_Bin
(30.009, 32.3]               0.504348      0.555556      0.601399
(32.3, 36.033]               0.534314      0.513228      0.630682
(36.033, 83.91]              0.401460      0.469945      0.488000

【Count】
BB_Width_Zscore20_Bin  (-2.231, 1.29]  (1.29, 2.86]  (2.86, 4.24]
Prev_RSI_Bin
(30.009, 32.3]                    230           198           143
(32.3, 36.033]                    204           189           176
(36.033, 83.91]                   137           183           250
================================================================================
Prev_RSI × Lower_Shadow_Pct

【WinRate】
Lower_Shadow_Pct_Bin  (1.999, 2.82]  (2.82, 4.247]  (4.247, 25.13]
Prev_RSI_Bin
(30.009, 32.3]             0.512690       0.500000        0.621212
(32.3, 36.033]             0.502825       0.565000        0.598958
(36.033, 83.91]            0.447236       0.418848        0.522222

【Count】
Lower_Shadow_Pct_Bin  (1.999, 2.82]  (2.82, 4.247]  (4.247, 25.13]
Prev_RSI_Bin
(30.009, 32.3]                  197            176             198
(32.3, 36.033]                  177            200             192